version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: finflow
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"

volumes:
  pgdata:
